Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,6 +52,30 @@ jobs:
       run: |
         kubectl get nodes
 
+    - name: Deploy Flask App
+      run: |
+        kubectl apply -f k8s/deployment.yaml
+        kubectl apply -f k8s/service.yaml
+        kubectl apply -f k8s/ingress.yaml
+
+    - name: Install ALB Ingress Controller
+      run: |
+         kubectl get deployment -n kube-system aws-load-balancer-controller || echo "Controller not found, proceeding with install"
+
+         helm repo add eks https://aws.github.io/eks-charts
+         helm repo update
+
+          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
+           -n kube-system \
+           --set clusterName=dev-eks \
+           --set serviceAccount.create=true \
+           --set serviceAccount.name=aws-load-balancer-controller \
+           --set region=ap-south-1 \
+           --set vpcId=vpc-063a82b96acf21fe0
+
+         kubectl get pods -n kube-system -l app.kubernetes.io/name=aws-load-balancer-controller
+         kubectl get endpoints -n kube-system aws-load-balancer-webhook-service
+
 
 
 
